### ISSUE TITLE
.all() method not working when using Orator ORM

### ISSUE THREAD

**Issue by joaobarbosa** [sdispater/orator-cache#3]
Trying to fetch all records from a model, like this: `User.remember(60).all()` raises a `AttributeError: all`. 

`User.all()` is working fine. Also, using `User.remember(60).get()` is working too.

**Comment by sdispater** [comment]
This is intended.

`all()` is a `Model` method. However, as soon as you use the `remember()` method, you have access to a `Builder` instance that doesn't have the `all()` method only the `get()` one.
